export const Projects = [
    {
        id: "project-1",
        image: "/images/rdis.png",
        title: "ROAD DEFECT DETECTION SYSTEM - RabBits",
        description: "System for detecting road defects using computer vision and machine learning.",
        tags: ["Python", "AI & Machine Learning", "PyQT", "YoloV10", "Google Cloud"],
        longDescription: "This advanced system leverages computer vision and machine learning to automatically detect and classify road defects. Built with Python and YoloV10, it provides real-time analysis of road conditions to help with infrastructure maintenance.",
        githubLink: "https://github.com/bntlyr/Road-Defect-Indexing-System",
        liveDemoLink: "",
        gallery: [
            "/images/rdis.png",
            "/images/rdis1.png",
            "/images/rdis2.png"
        ],
    },
    {
        id: "project-2",
        image: "/images/kape.png",
        title: "Kape ni Rab",
        description: "Kape ni Rab! was the champion website developed in just two days during the Codetober: Web Development Competition hosted by the FEU Tech Alliance of Information Technology Students in October 2024.",
        tags: ["JavaScript", "TypeScript", "HTML", "Tailwind CSS", "Next.js"],
        longDescription: "Champion website developed in just two days during the Codetober competition. Features modern design, responsive layout, and optimized performance built with Next.js and Tailwind CSS.",
        githubLink: "https://github.com/alpharomercoma/kape",
        liveDemoLink: "",
        gallery: [
            "/images/kape.png",
        ],
    },
    {
        id: "project-3",
        image: "/images/Gradecal.png",
        title: "GradeCal For FEUTECH SOLAR Portal",
        description: "Browser extension for calculating and tracking academic grades for FEU students using the SOLAR portal.",
        tags: ["JavaScript", "CSS", "HTML", "Chrome Extension API"],
        longDescription: "A powerful browser extension designed specifically for FEU Tech students to calculate and track their academic grades seamlessly through the SOLAR portal. Features automatic grade computation and progress tracking.",
        githubLink: "",
        liveDemoLink: "https://chromewebstore.google.com/detail/gradecal/gaemamkhhodofhfhmicimlefchefgmeo",
        gallery: [
            "/images/Gradecal.png",
            "/images/Gradecal1.png",
            "/images/Gradecal2.png"
        ],
    },
    {
        id: "project-4", 
        image: "/images/puto.png",
        title: "Puto-Order System",
        description: "Simple Puto-Order System for managing orders of small family business.",
        tags: ["JavaScript", "TypeScript", "Next.JS", "indexedDB", "HTML", "Tailwind CSS"],
        longDescription: "A comprehensive order management system designed for small family businesses. Features inventory tracking, order processing, and customer management with offline capabilities using IndexedDB.",
        githubLink: "",
        liveDemoLink: "",
        gallery: [
            "/images/puto.png",
        ],
    },
    {
        id: "project-5",
        image: "/images/solarpal.png",
        title: "SolarPal - Solar Potential Map",
        description: "A web application to help Filipinos find optimal solar panel locations using NASA POWER solar irradiance data.",
        tags: ["TypeScript","JavaScript", "FastAPI", "React", "Next.js","PostGreSQL", "Python", "Nasa Power API"],
        longDescription: "Project SolarPal is an interactive web platform that helps Filipinos identify the best locations for solar panel installation using NASA’s solar irradiance data. Developed by Team Solourn, it visualizes sunlight exposure across the Philippines through an intuitive, map-based interface that allows users to explore, search, or analyze specific coordinates for solar potential. ",
        githubLink: "https://github.com/bntlyr/SolarPal",
        liveDemoLink: "https://solarpal-delta.vercel.app/",
        gallery: [
            "/images/solarpal.png",
            "/images/solarpal1.png"
        ],
    },
    {
        id: "project-6",
        image: "/images/manhwaseen.jpg",
        title: "ManhwaSeen - Forum App",
        description: "ManhwaSeen is an online community platform for manhwa lovers to discover new titles, share reviews, and connect with fellow readers.",
        tags: ["TypeScript","JavaScript", "Supabase", "React", "PostGreSQL", "Next.JS"],
        longDescription: "ManhwaSeen is an online community platform for manhwa lovers to discover new titles, share reviews, and connect with fellow readers. It features a dedicated forum for discussions, recommendations, and social interaction, as well as a personalized library for tracking and storing manhwas you’ve read. Designed to be a one-stop hub for both casual readers and passionate fans, ManhwaSeen helps users find their next great read while fostering a vibrant, engaged community.",
        githubLink: "https://github.com/bntlyr/manhwaseen",
        liveDemoLink: "https://manhwaseen.vercel.app/",
        gallery: [
            "/images/manhwaseen.jpg",
        ],
    },
        {
        id: "project-7",
        image: "/images/mochi.png",
        title: "MochiBoard",
        description: "Collaborative dashboard web application for project management and team coordination.",
        tags: ["TypeScript","React", "Node.js", "Next.JS", "PostGreSQL", "Tailwind CSS"],
        longDescription: "A comprehensive collaborative dashboard designed for modern project management and team coordination. Features real-time updates, task tracking, and seamless team communication tools.",
        githubLink: "https://github.com/bntlyr/mochiboard",
        liveDemoLink: "https://mochiboard.vercel.app",
        gallery: [
            "/images/mochi.png",
        ],
    },
    {
        id: "project-8",
        image: "/images/forum.png",
        title: "Acmx Forum Page",
        description: "Interactive forum web application for community discussions and engagement.",
        tags: ["JavaScript", "TypeScript", "Next.JS", "PostgreSQL", "Tailwind CSS", "Prisma ORM"],
        longDescription: "A modern forum application built with Next.js and PostgreSQL, featuring real-time discussions, user authentication, and community engagement tools. Designed for seamless user interaction and content management.",
        githubLink: "https://github.com/bntlyr/acmx",
        liveDemoLink: "",
        gallery: [
            "/images/forum.png",
        ],
    },
    {
        id: "project-9",
        image: "/images/zof.png",
        title: "LAEEA - Learning and Education Enhancement Application",
        description: "AI-powered web application with intelligent features and machine learning capabilities.",
        tags: ["AI & Machine Learning", "Next.JS","TypeScript", "JavaScript", "GEMINI API"],
        longDescription: "An innovative AI-powered educational platform that enhances learning experiences through intelligent tutoring, personalized content, and adaptive learning paths. Integrated with Google's Gemini API for advanced AI capabilities.",
        githubLink: "https://github.com/example/laeea",
        liveDemoLink: "https://laeea.vercel.app",
        gallery: [
            "/images/zof.png",
        ],
    },
    {
        id: "project-10",
        image: "/images/deceit.jpg",
        title: "Deceit",
        description: "Interactive game with engaging gameplay mechanics and immersive user experience.",
        tags: ["C#", "Unity", "Game Development"],
        longDescription: "An immersive interactive game built with Unity and C#, featuring engaging gameplay mechanics, stunning visuals, and intuitive controls. Designed to provide players with an unforgettable gaming experience.",
        githubLink: "https://github.com/bntlyr/Deceit-2D-RPG-Adventure",
        liveDemoLink: "",
        gallery: [
            "/images/deceit.jpg",
        ],
    },
    {
        id: "project-11",
        image: "/images/codle.png",
        title: "CODLE - Guessing Game",
        description: "Fun and interactive guessing game with multiple difficulty levels and scoring system.",
        tags: ["JAVA"],
        longDescription: "A fun and challenging guessing game built with Java, featuring multiple difficulty levels, scoring system, and engaging gameplay mechanics. Perfect for users looking for an entertaining and educational experience.",
        githubLink: "https://github.com/bntlyr/GUESSING-GAME",
        liveDemoLink: "",
        gallery: [
            "/images/codle.png",
        ],
    },
    {
        id: "project-12",
        image: "/images/thelib.png",
        title: "TheLib - Manga Tracker",
        description: "Browser extension and web application for tracking manga reading progress and managing collections.",
        tags: ["TypeScript","JavaScript", "Chrome Extension API", "React", "PostGreSQL", "Google Cloud"],
        longDescription: "A comprehensive manga tracking solution combining a browser extension and web application. Track reading progress, manage collections, and discover new series with advanced search and recommendation features.",
        githubLink: "https://github.com/bntlyr/thelib",
        liveDemoLink: "https://thelib.vercel.app",
        gallery: [
            "/images/thelib.png",
        ],
    },
]

export const Skills = {
    languages: [
        { name: "C++", level: 60 },
        { name: "Java", level: 75 },
        { name: "Python", level: 85 },
        { name: "Javascript / Typescript", level: 85 },
        { name: "C#", level: 20 },
        { name: "PHP", level: 45 },
        { name: "HTML/CSS", level: 90 },
        { name: "SQL", level: 85 },
        { name: "Flutter", level: 35 },
        { name: "Kotlin", level: 65 },
    ],
    frameworks: ["React", "Next.JS", "Flask", "DJango", "PyQT", ".NET", "Angular"],
    tools: ["Git", "VS Code", "Figma", "Docker", "AWS", "Azure", "Rest APIs", "FastAPI","GraphQL", "Googe Cloud Platform"],
    databases: ["PostgreSQL", "MySQL", "Firebase", "Supabase", "Neon", "Prisma ORM"]
}
